// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpGmiTX9nefDc3hojVN9H9h1Opg8XBXr4',
    appId: '1:903590250434:web:62866bde08c196b72ab85b',
    messagingSenderId: '903590250434',
    projectId: 'likes-abd63',
    authDomain: 'likes-abd63.firebaseapp.com',
    databaseURL: 'https://likes-abd63-default-rtdb.firebaseio.com',
    storageBucket: 'likes-abd63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW3twQ9YeANu3MkobcwsplhECEUmfCEvY',
    appId: '1:903590250434:android:864ad2a8a20a9c6a2ab85b',
    messagingSenderId: '903590250434',
    projectId: 'likes-abd63',
    databaseURL: 'https://likes-abd63-default-rtdb.firebaseio.com',
    storageBucket: 'likes-abd63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsfSRCMaYthbZ3kD37NiH39Q-viE1k8RQ',
    appId: '1:903590250434:ios:460cef1d52943f1c2ab85b',
    messagingSenderId: '903590250434',
    projectId: 'likes-abd63',
    databaseURL: 'https://likes-abd63-default-rtdb.firebaseio.com',
    storageBucket: 'likes-abd63.appspot.com',
    iosClientId: '903590250434-6cj93q62uuu6qs63591vlipuetici1gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.likes',
  );
}
